# Generated by Django 2.0.7 on 2020-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200505_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, height_field=20, null=True, upload_to='image/', width_field=20),
        ),
    ]
